"""Casos train/val hechos a mano para flujo-intents (sin generador).

Cada caso es una ficha explicita, inspirada en el estilo de los originales del
proyecto de gobierno pero con contenido distinto, etiquetada para una etapa. Este
modulo es la SSOT del train/val; al ejecutarse escribe los CSV de variaciones que
`dataset.py` consume:

    python -m dspy_gepa_poc.flujo_intents.make_variations

Los 42 originales NO se tocan: son el holdout de test (recortado a 30 por etapa).
Aqui se autoran train (30) + val (15) por etapa, balanceados por clase. El helper
`case` defaultea los campos no decisivos para mantener cada caso compacto; el texto
se concentra en los campos que definen la clase de esa etapa.
"""

from __future__ import annotations

import csv
from collections.abc import Iterable
from pathlib import Path

# tipo de intent -> columna booleana
_TIPO = {
    "negocio": "tipo_intent_negocio",
    "operativo": "tipo_intent_operativo",
    "capacidad": "tipo_intent_capacidad_equipos",
    "tecnico": "tipo_intent_tecnico_arquitectural",
}
# categoria de datos -> columna booleana
_DATOS = {
    "ninguno": "datos_requeridos_ninguno",
    "publicos": "datos_requeridos_datos_publicos",
    "operativos": "datos_requeridos_datos_operativos",
    "personales": "datos_requeridos_datos_personales",
    "confidenciales": "datos_requeridos_datos_confidenciales",
    "otros": "datos_requeridos_otros",
}

_FICHA_COLS = [
    "id",
    "nombre_iniciativa",
    *_TIPO.values(),
    "declaracion_intent",
    "area_proponente",
    "flujo_de_valor",
    "metricas_de_exito",
    "impacto_personas",
    *_DATOS.values(),
    "supuesto_riesgo",
    "restricciones",
    "sponsor",
]

# Defaults de los campos NO decisivos (se sobreescriben solo cuando importan).
_DEF_IMPACTO = "Empleados como usuarios; no decide sobre personas. Criticidad baja."
_DEF_RIESGO = "El modelo del catalogo es adecuado; hay revision humana previa."
_DEF_RESTR = "Sin datos personales; revision humana previa; presupuesto acotado."
_DEF_METRICAS = "Reduccion de tiempo >= 40% (linea base 10h/mes; meta 6h/mes)"
_DEF_SPONSOR = "Gerente de Area (persona accountable)"


def case(
    cid: str,
    tipo: str,
    datos: Iterable[str],
    label: str,
    split: str,
    decl: str,
    *,
    nombre: str | None = None,
    area: str = "Operaciones",
    flujo: str = "Proceso interno del area",
    metricas: str = _DEF_METRICAS,
    impacto: str = _DEF_IMPACTO,
    riesgo: str = _DEF_RIESGO,
    restr: str = _DEF_RESTR,
    sponsor: str = _DEF_SPONSOR,
    razonamiento: str = "",
) -> dict[str, str]:
    row: dict[str, str] = dict.fromkeys(_TIPO.values(), "false")
    row.update(dict.fromkeys(_DATOS.values(), "false"))
    row[_TIPO[tipo]] = "true"
    for d in datos:
        row[_DATOS[d]] = "true"
    row.update(
        id=cid,
        nombre_iniciativa=nombre or cid,
        declaracion_intent=decl,
        area_proponente=area,
        flujo_de_valor=flujo,
        metricas_de_exito=metricas,
        impacto_personas=impacto,
        supuesto_riesgo=riesgo,
        restricciones=restr,
        sponsor=sponsor,
        label=label,
        split=split,
        razonamiento=razonamiento,
    )
    return row


# ===========================================================================
# INTAKE: admitida vs incompleta (campo minimo ausente o contradiccion interna)
# ===========================================================================
INTAKE = [
    # --- incompleta: campo de texto minimo ausente (override a "") ---
    case(
        "VAR-INT-I01",
        "operativo",
        ["operativos"],
        "incompleta",
        "train",
        "",
        nombre="Clasificador de tickets",
        area="Soporte",
        metricas="Reduccion del tiempo de primera respuesta de 8h a 2h",
        impacto="Agentes de soporte como usuarios; el cliente recibe la derivacion. Criticidad media.",
        sponsor="Jefe de Mesa de Ayuda (persona accountable)",
    ),
    case(
        "VAR-INT-I02",
        "negocio",
        ["personales"],
        "incompleta",
        "train",
        "Sistema que recomienda ofertas al cliente.",
        sponsor="",
    ),
    case(
        "VAR-INT-I03",
        "operativo",
        ["confidenciales"],
        "incompleta",
        "train",
        "Sistema que resume reportes financieros internos.",
        metricas="",
    ),
    case(
        "VAR-INT-I04",
        "operativo",
        ["operativos"],
        "incompleta",
        "train",
        "Sistema que prioriza ordenes de trabajo.",
        impacto="",
    ),
    case(
        "VAR-INT-I05",
        "capacidad",
        ["ninguno"],
        "incompleta",
        "train",
        "Asistente que redacta minutas internas.",
        flujo="",
    ),
    case(
        "VAR-INT-I06",
        "operativo",
        ["operativos"],
        "incompleta",
        "train",
        "Detector de anomalias en logs de red.",
        area="",
    ),
    case(
        "VAR-INT-I07",
        "negocio",
        ["personales"],
        "incompleta",
        "train",
        "Motor de scoring de clientes.",
        riesgo="",
    ),
    case(
        "VAR-INT-I08",
        "operativo",
        ["confidenciales"],
        "incompleta",
        "train",
        "Resumen de contratos internos.",
        restr="",
    ),
    case(
        "VAR-INT-I09",
        "operativo",
        ["operativos"],
        "incompleta",
        "train",
        "",
        nombre="Asistente de inventario",
        area="Logistica",
        metricas="Reduccion de quiebres de stock del 15% al 5%",
        impacto="Equipo de logistica como usuario; no decide sobre personas. Criticidad baja.",
        riesgo="Modelo de pronostico estandar; el planner valida los pedidos sugeridos.",
        sponsor="Gerente de Logistica (persona accountable)",
    ),
    case(
        "VAR-INT-I10",
        "negocio",
        ["personales"],
        "incompleta",
        "train",
        "Recomendador de planes.",
        sponsor="",
    ),
    # --- incompleta: contradiccion interna irreconciliable ---
    case(
        "VAR-INT-I11",
        "negocio",
        ["ninguno"],
        "incompleta",
        "train",
        "Sistema que analiza historial de pagos y perfil crediticio del cliente para recomendar productos.",
        restr="Sin datos personales.",
    ),
    case(
        "VAR-INT-I12",
        "operativo",
        ["ninguno"],
        "incompleta",
        "train",
        "Agente que procesa datos personales de empleados para asignar turnos.",
        impacto="Empleados afectados.",
    ),
    case(
        "VAR-INT-I13",
        "negocio",
        ["personales"],
        "incompleta",
        "train",
        "Sistema puramente informativo que no accede a ningun dato del cliente ni de terceros.",
        restr="No usa datos.",
    ),
    case(
        "VAR-INT-I14",
        "operativo",
        ["confidenciales"],
        "incompleta",
        "train",
        "Herramienta que no procesa informacion alguna, solo muestra un calendario fijo.",
    ),
    case(
        "VAR-INT-I15",
        "operativo",
        ["operativos"],
        "incompleta",
        "train",
        "",
        nombre="Bot de reportes",
        area="Finanzas",
        metricas="Cierre mensual en 1 dia en lugar de 4",
        impacto="Analistas de finanzas como usuarios; reportes internos. Criticidad media.",
        restr="Datos financieros confidenciales; acceso restringido al equipo de Finanzas.",
        sponsor="Gerente de Finanzas (persona accountable)",
    ),
    # incompleta val
    case(
        "VAR-INT-I16",
        "negocio",
        ["personales"],
        "incompleta",
        "val",
        "Asistente comercial.",
        metricas="",
    ),
    case(
        "VAR-INT-I17",
        "operativo",
        ["operativos"],
        "incompleta",
        "val",
        "Clasificador de correos.",
        sponsor="",
    ),
    case(
        "VAR-INT-I18",
        "operativo",
        ["confidenciales"],
        "incompleta",
        "val",
        "",
        nombre="Analizador de costos",
        area="Finanzas",
        metricas="Identificacion del 90% de desvios de costo > 5%",
        impacto="Controllers como usuarios; marca desvios para revision. Criticidad media.",
        riesgo="Reglas de deteccion auditadas; control de gestion revisa cada alerta.",
        restr="Informacion de costos confidencial; segregacion de funciones.",
        sponsor="Controller (persona accountable)",
    ),
    case(
        "VAR-INT-I19",
        "negocio",
        ["ninguno"],
        "incompleta",
        "val",
        "Sistema que usa datos de facturacion y consumo del cliente para segmentar.",
        restr="Sin datos personales.",
    ),
    case(
        "VAR-INT-I20",
        "capacidad",
        ["ninguno"],
        "incompleta",
        "val",
        "Asistente de documentacion.",
        flujo="",
    ),
    case(
        "VAR-INT-I21",
        "operativo",
        ["operativos"],
        "incompleta",
        "val",
        "Optimizador de rutas.",
        impacto="",
    ),
    case(
        "VAR-INT-I22", "negocio", ["personales"], "incompleta", "val", "Motor de upsell.", riesgo=""
    ),
    # --- admitida: ficha completa y consistente (riesgo variado, todo declarado) ---
    case(
        "VAR-INT-A01",
        "capacidad",
        ["ninguno"],
        "admitida",
        "train",
        "Asistente que genera borradores de documentacion tecnica a partir de notas del equipo; el autor revisa.",
        nombre="Asistente de docs",
        area="Ingenieria",
    ),
    case(
        "VAR-INT-A02",
        "operativo",
        ["confidenciales"],
        "admitida",
        "train",
        "Sistema que resume reportes de gestion confidenciales y marca desvios; la gerencia valida.",
        nombre="Resumen gerencial",
        area="Planificacion",
    ),
    case(
        "VAR-INT-A03",
        "negocio",
        ["personales"],
        "admitida",
        "train",
        "Sistema que sugiere ofertas al representante segun el consumo del cliente; el representante decide.",
        nombre="Recomendador asistido",
        area="Ventas",
        impacto="Clientes via representante; el representante decide. Criticidad media.",
        restr="Cumplimiento Ley 25.326; el representante decide.",
    ),
    case(
        "VAR-INT-A04",
        "operativo",
        ["operativos"],
        "admitida",
        "train",
        "Sistema que prioriza incidencias por severidad para el equipo tecnico; el equipo decide.",
        nombre="Triage de incidencias",
        area="Soporte",
    ),
    case(
        "VAR-INT-A05",
        "operativo",
        ["confidenciales"],
        "admitida",
        "train",
        "Sistema que detecta anomalias de costos y las marca para revision de Finanzas.",
        nombre="Anomalias de costos",
        area="Finanzas",
    ),
    case(
        "VAR-INT-A06",
        "capacidad",
        ["ninguno"],
        "admitida",
        "train",
        "Asistente que redacta borradores de comunicados internos; el responsable aprueba antes de publicar.",
        nombre="Asistente comunicados",
        area="Comunicaciones",
    ),
    case(
        "VAR-INT-A07",
        "negocio",
        ["personales"],
        "admitida",
        "train",
        "Chatbot que responde consultas del cliente sobre su plan en plataforma interna homologada; escala a humano.",
        nombre="Chatbot de plan",
        area="Atencion",
        impacto="Clientes que interactuan. Criticidad alta.",
        restr="Cumplimiento Ley 25.326; escalada a humano fuera de dominio.",
    ),
    case(
        "VAR-INT-A08",
        "operativo",
        ["operativos"],
        "admitida",
        "train",
        "Sistema de monitoreo que alerta al equipo de red ante desvios; el equipo decide intervenir.",
        nombre="Monitoreo de red",
        area="Infraestructura",
    ),
    case(
        "VAR-INT-A09",
        "tecnico",
        ["operativos"],
        "admitida",
        "train",
        "Pipeline que clasifica logs de plataforma para mejorar la observabilidad interna.",
        nombre="Clasificador de logs",
        area="Plataforma",
    ),
    case(
        "VAR-INT-A10",
        "operativo",
        ["confidenciales"],
        "admitida",
        "train",
        "Sistema que analiza contratos internos e identifica clausulas de riesgo; el abogado valida.",
        nombre="Analizador de clausulas",
        area="Legal",
        impacto="Abogados como consumidores. Criticidad alta.",
        restr="Confidencialidad contractual; el abogado valida cada hallazgo.",
    ),
    case(
        "VAR-INT-A11",
        "negocio",
        ["personales"],
        "admitida",
        "train",
        "Sistema que calcula score crediticio con API externa por homologar; el analista registra la decision.",
        nombre="Scoring credito",
        area="Credito",
        impacto="Clientes solicitantes; el score condiciona el acceso. Criticidad muy alta.",
        riesgo="La API externa sera homologada antes de produccion.",
        restr="Cumplimiento BCRA; el analista decide; sin variables discriminatorias.",
    ),
    case(
        "VAR-INT-A12",
        "operativo",
        ["personales"],
        "admitida",
        "train",
        "Agente que envia comunicaciones de bienvenida predefinidas al activar un plan; contenido aprobado.",
        nombre="Onboarding",
        area="Activacion",
        impacto="Clientes nuevos. Criticidad media.",
        restr="Cumplimiento Ley 25.326; plantillas aprobadas.",
    ),
    case(
        "VAR-INT-A13",
        "operativo",
        ["operativos"],
        "admitida",
        "train",
        "Sistema que sugiere asignacion de turnos al supervisor; el supervisor aprueba.",
        nombre="Asignacion de turnos",
        area="Operaciones",
    ),
    case(
        "VAR-INT-A14",
        "capacidad",
        ["ninguno"],
        "admitida",
        "train",
        "Asistente que genera consultas SQL a partir de pedidos en lenguaje natural del analista interno.",
        nombre="Asistente SQL",
        area="Datos",
    ),
    case(
        "VAR-INT-A15",
        "operativo",
        ["confidenciales"],
        "admitida",
        "train",
        "Sistema que resume actas de directorio para los participantes; ellos validan antes de distribuir.",
        nombre="Resumen de actas",
        area="Secretaria",
        restr="Confidencial; participantes validan.",
    ),
    # admitida val
    case(
        "VAR-INT-A16",
        "capacidad",
        ["ninguno"],
        "admitida",
        "val",
        "Asistente que propone respuestas a tickets internos; el agente revisa antes de enviar.",
        nombre="Asistente tickets",
        area="Soporte",
    ),
    case(
        "VAR-INT-A17",
        "operativo",
        ["confidenciales"],
        "admitida",
        "val",
        "Sistema que genera tableros de costos para gerentes; ninguna decision sobre personas depende del output.",
        nombre="Tablero de costos",
        area="Finanzas",
    ),
    case(
        "VAR-INT-A18",
        "negocio",
        ["personales"],
        "admitida",
        "val",
        "Sistema que recomienda upgrades al representante; el representante decide que ofrecer.",
        nombre="Recomendador upgrade",
        area="Atencion",
        impacto="Clientes via representante. Criticidad media.",
        restr="Cumplimiento Defensa del Consumidor; el representante decide.",
    ),
    case(
        "VAR-INT-A19",
        "operativo",
        ["operativos"],
        "admitida",
        "val",
        "Sistema que detecta fraude potencial y lo marca para el equipo de riesgos; el equipo decide.",
        nombre="Deteccion de fraude",
        area="Riesgos",
    ),
    case(
        "VAR-INT-A20",
        "tecnico",
        ["operativos"],
        "admitida",
        "val",
        "Pipeline que evalua la calidad de datos de ingestion y reporta al equipo de datos.",
        nombre="Calidad de datos",
        area="Datos",
    ),
    case(
        "VAR-INT-A21",
        "capacidad",
        ["ninguno"],
        "admitida",
        "val",
        "Asistente que resume papers tecnicos para el equipo de investigacion interna.",
        nombre="Resumen tecnico",
        area="I+D",
    ),
    case(
        "VAR-INT-A22",
        "operativo",
        ["confidenciales"],
        "admitida",
        "val",
        "Sistema que analiza encuestas internas de clima y reporta tendencias agregadas a RRHH.",
        nombre="Analisis de clima",
        area="RRHH",
        restr="Datos agregados; sin identificar individuos.",
    ),
    case(
        "VAR-INT-A23",
        "operativo",
        ["personales"],
        "admitida",
        "val",
        "Sistema que genera un resumen del historial del cliente para el representante; es informativo.",
        nombre="Resumen de historial",
        area="Atencion",
        impacto="Representantes como usuarios; informativo. Criticidad media.",
        restr="Cumplimiento Ley 25.326; el representante decide.",
    ),
]


# ===========================================================================
# TRIAGE_SOLIDEZ: solido / devolucion_reformulacion (2 clases del Marco; salida Si/No)
# (la ficha ya fue admitida: completa; aqui se juzga la solidez del intent)
# devolucion_no_ia ("no requiere IA") y "valor real" se retiraron: no son criterios de
# solidez del Marco; van a etapas nuevas (diferidas, D-014).
# ===========================================================================
def _sol(cid, tipo, datos, label, split, decl, **kw):  # noqa: ANN001, ANN003
    return case(cid, tipo, datos, label, split, decl, **kw)


SOLIDEZ = [
    # solido (10 train + 5 val): resultado claro, sponsor individual, metricas medibles, requiere IA
    _sol(
        "VAR-SOL-S01",
        "operativo",
        ["confidenciales"],
        "solido",
        "train",
        "Sistema que detecta anomalias de costos por centro y las marca para Finanzas; reduce el tiempo de revision.",
        metricas="Deteccion de anomalias >= 80% (linea base 55%); tiempo -50%",
    ),
    _sol(
        "VAR-SOL-S02",
        "capacidad",
        ["ninguno"],
        "solido",
        "train",
        "Asistente que genera borradores de minutas a partir de transcripciones; el autor valida.",
        metricas="Tiempo de documentacion -60% (de 90 a 36 min); satisfaccion >= 4/5",
    ),
    _sol(
        "VAR-SOL-S03",
        "negocio",
        ["personales"],
        "solido",
        "train",
        "Sistema que resume el historial del cliente para el representante antes de la llamada; es informativo.",
        metricas="Tiempo de preparacion -50%; satisfaccion del representante >= 4/5",
    ),
    _sol(
        "VAR-SOL-S04",
        "operativo",
        ["operativos"],
        "solido",
        "train",
        "Sistema que prioriza tickets por severidad y los rutea al equipo correcto; el equipo decide.",
        metricas="Tiempo de primera respuesta -40% (de 8h a 5h)",
    ),
    _sol(
        "VAR-SOL-S05",
        "operativo",
        ["confidenciales"],
        "solido",
        "train",
        "Sistema que resume reportes de gestion y marca desvios para la gerencia; la gerencia valida.",
        metricas="Tiempo de resumen < 2h; precision de desvios >= 85%",
    ),
    _sol(
        "VAR-SOL-S06",
        "tecnico",
        ["operativos"],
        "solido",
        "train",
        "Pipeline que clasifica logs para mejorar la observabilidad del equipo de plataforma.",
        metricas="Cobertura de clasificacion >= 90%; MTTR -30%",
    ),
    _sol(
        "VAR-SOL-S07",
        "negocio",
        ["personales"],
        "solido",
        "train",
        "Chatbot que responde consultas del cliente sobre su plan; escala a humano fuera de dominio.",
        metricas="Resolucion sin escalada >= 70%; CSAT >= 4/5",
    ),
    _sol(
        "VAR-SOL-S08",
        "operativo",
        ["confidenciales"],
        "solido",
        "train",
        "Sistema que identifica clausulas de riesgo en contratos para el equipo legal; el abogado valida.",
        metricas="Cobertura de clausulas >= 90%; falsos negativos < 5%",
    ),
    _sol(
        "VAR-SOL-S09",
        "capacidad",
        ["ninguno"],
        "solido",
        "train",
        "Asistente que genera consultas SQL desde lenguaje natural para el analista; el analista revisa.",
        metricas="Tiempo de consulta -55%; consultas correctas >= 85%",
    ),
    _sol(
        "VAR-SOL-S10",
        "operativo",
        ["operativos"],
        "solido",
        "train",
        "Sistema que predice demanda de stock para sugerir reposicion al comprador; el comprador decide.",
        metricas="Quiebres de stock -35%; exactitud de pronostico >= 80%",
    ),
    _sol(
        "VAR-SOL-S11",
        "operativo",
        ["confidenciales"],
        "solido",
        "val",
        "Sistema que resume encuestas internas y reporta tendencias agregadas a RRHH.",
        metricas="Tiempo de analisis -50%; cobertura de encuestas 100%",
    ),
    _sol(
        "VAR-SOL-S12",
        "negocio",
        ["personales"],
        "solido",
        "val",
        "Sistema que sugiere ofertas al representante segun consumo; el representante decide.",
        metricas="Conversion >= 12%; NPS sin deterioro",
    ),
    _sol(
        "VAR-SOL-S13",
        "operativo",
        ["operativos"],
        "solido",
        "val",
        "Sistema que detecta fraude potencial y lo marca para el equipo de riesgos; el equipo decide.",
        metricas="Deteccion de fraude +20%; falsos positivos < 8%",
    ),
    _sol(
        "VAR-SOL-S14",
        "capacidad",
        ["ninguno"],
        "solido",
        "val",
        "Asistente que redacta borradores de comunicados internos; el responsable aprueba.",
        metricas="Tiempo de redaccion -50%; aprobacion sin cambios >= 70%",
    ),
    _sol(
        "VAR-SOL-S15",
        "tecnico",
        ["operativos"],
        "solido",
        "val",
        "Pipeline que evalua calidad de datos de ingestion y reporta al equipo de datos.",
        metricas="Registros inconsistentes -80%; cobertura 100%",
    ),
    # solido -- ampliacion balanceada (4 train + 5 val + 10 test) para 2 clases del Marco
    _sol(
        "VAR-SOL-S16",
        "operativo",
        ["confidenciales"],
        "solido",
        "train",
        "Sistema que clasifica correos de clientes por intencion y los rutea al equipo; el equipo decide.",
        metricas="Precision de ruteo >= 85%; tiempo de derivacion -40%",
    ),
    _sol(
        "VAR-SOL-S17",
        "capacidad",
        ["ninguno"],
        "solido",
        "train",
        "Asistente que resume documentacion tecnica para el equipo de I+D; el investigador valida.",
        metricas="Tiempo de revision -50%; satisfaccion >= 4/5",
    ),
    _sol(
        "VAR-SOL-S18",
        "negocio",
        ["personales"],
        "solido",
        "train",
        "Sistema que detecta churn potencial y lo marca para el equipo de retencion; el equipo decide.",
        metricas="Deteccion de churn >= 75%; falsos positivos < 10%",
    ),
    _sol(
        "VAR-SOL-S19",
        "operativo",
        ["operativos"],
        "solido",
        "train",
        "Sistema que predice fallas de equipos para mantenimiento preventivo; el tecnico valida.",
        metricas="Fallas no planificadas -30%; exactitud >= 80%",
    ),
    _sol(
        "VAR-SOL-S20",
        "operativo",
        ["confidenciales"],
        "solido",
        "val",
        "Sistema que extrae datos clave de facturas de proveedores para el contador; el contador valida.",
        metricas="Exactitud de extraccion >= 90%; tiempo -50%",
    ),
    _sol(
        "VAR-SOL-S21",
        "capacidad",
        ["ninguno"],
        "solido",
        "val",
        "Asistente que genera casos de prueba a partir de requisitos para QA; el QA revisa.",
        metricas="Cobertura de pruebas +25%; tiempo de diseno -40%",
    ),
    _sol(
        "VAR-SOL-S22",
        "negocio",
        ["personales"],
        "solido",
        "val",
        "Sistema que segmenta clientes y sugiere campanias al responsable de marketing; el responsable decide.",
        metricas="Conversion +10%; sin deterioro de NPS",
    ),
    _sol(
        "VAR-SOL-S23",
        "operativo",
        ["operativos"],
        "solido",
        "val",
        "Sistema que detecta anomalias de trafico de red y alerta al SOC; el SOC decide.",
        metricas="Deteccion >= 80%; falsos positivos < 8%",
    ),
    _sol(
        "VAR-SOL-S24",
        "tecnico",
        ["operativos"],
        "solido",
        "val",
        "Sistema que clasifica logs de error por causa raiz para el equipo de plataforma.",
        metricas="Tiempo de diagnostico -45%; precision >= 85%",
    ),
    _sol(
        "TST-SOL-S01",
        "operativo",
        ["confidenciales"],
        "solido",
        "test",
        "Sistema que resume contratos para el area legal; el abogado valida cada resumen.",
        metricas="Tiempo de revision -55%; cobertura de clausulas >= 90%",
    ),
    _sol(
        "TST-SOL-S02",
        "capacidad",
        ["ninguno"],
        "solido",
        "test",
        "Asistente que documenta codigo para los desarrolladores; el dev revisa.",
        metricas="Tiempo de documentacion -50%; aceptacion >= 80%",
    ),
    _sol(
        "TST-SOL-S03",
        "negocio",
        ["personales"],
        "solido",
        "test",
        "Sistema que prioriza leads para el vendedor segun probabilidad de cierre; el vendedor decide.",
        metricas="Tasa de cierre +15%; tiempo de calificacion -40%",
    ),
    _sol(
        "TST-SOL-S04",
        "operativo",
        ["operativos"],
        "solido",
        "test",
        "Sistema que pronostica demanda para el planificador; el planificador decide la reposicion.",
        metricas="Error de pronostico < 15%; quiebres de stock -30%",
    ),
    _sol(
        "TST-SOL-S05",
        "operativo",
        ["confidenciales"],
        "solido",
        "test",
        "Sistema que detecta gastos atipicos para el equipo de auditoria; el auditor valida.",
        metricas="Deteccion >= 80%; falsos positivos < 10%",
    ),
    _sol(
        "TST-SOL-S06",
        "capacidad",
        ["ninguno"],
        "solido",
        "test",
        "Asistente que traduce documentacion tecnica para el equipo; el autor valida.",
        metricas="Tiempo de traduccion -60%; calidad >= 4/5",
    ),
    _sol(
        "TST-SOL-S07",
        "negocio",
        ["personales"],
        "solido",
        "test",
        "Sistema que resume interacciones del cliente para el agente antes del contacto; es informativo.",
        metricas="Tiempo de preparacion -50%; CSAT >= 4/5",
    ),
    _sol(
        "TST-SOL-S08",
        "operativo",
        ["operativos"],
        "solido",
        "test",
        "Sistema que clasifica incidentes por severidad para el NOC; el NOC decide.",
        metricas="Tiempo de triage -40%; precision >= 85%",
    ),
    _sol(
        "TST-SOL-S09",
        "tecnico",
        ["operativos"],
        "solido",
        "test",
        "Sistema que detecta degradacion de performance y alerta al equipo de plataforma.",
        metricas="MTTR -30%; deteccion temprana >= 80%",
    ),
    _sol(
        "TST-SOL-S10",
        "operativo",
        ["confidenciales"],
        "solido",
        "test",
        "Sistema que identifica clausulas faltantes en contratos para revision legal; el abogado decide.",
        metricas="Cobertura >= 90%; falsos negativos < 5%",
    ),
    # devolucion_reformulacion (10 train + 5 val): tecnologia-no-resultado / sponsor colectivo / metricas no medibles
    _sol(
        "VAR-SOL-R01",
        "negocio",
        ["personales"],
        "devolucion_reformulacion",
        "train",
        "Implementar GPT-4 en el canal de atencion para automatizar respuestas.",
        metricas="Implementacion en Q3; adopcion >= 80%",
    ),
    _sol(
        "VAR-SOL-R02",
        "operativo",
        ["operativos"],
        "devolucion_reformulacion",
        "train",
        "Implementar un modelo de Hugging Face en el area de soporte.",
        metricas="Despliegue completo en Q2",
    ),
    _sol(
        "VAR-SOL-R03",
        "negocio",
        ["personales"],
        "devolucion_reformulacion",
        "train",
        "Adoptar Llama 3 para el equipo comercial.",
        metricas="Uso del modelo >= 80%",
    ),
    _sol(
        "VAR-SOL-R04",
        "operativo",
        ["confidenciales"],
        "devolucion_reformulacion",
        "train",
        "Sistema que mejora la experiencia y reduce tiempos del proceso de reclamos.",
        metricas="Mejorar la experiencia; reducir tiempos; aumentar la eficiencia",
    ),
    _sol(
        "VAR-SOL-R05",
        "operativo",
        ["operativos"],
        "devolucion_reformulacion",
        "train",
        "Sistema que optimiza la gestion de inventario.",
        metricas="Optimizar el inventario; mejorar la disponibilidad",
    ),
    _sol(
        "VAR-SOL-R06",
        "negocio",
        ["personales"],
        "devolucion_reformulacion",
        "train",
        "Sistema que aumenta las ventas y la satisfaccion del cliente.",
        metricas="Aumentar ventas; mejorar satisfaccion",
    ),
    _sol(
        "VAR-SOL-R07",
        "operativo",
        ["confidenciales"],
        "devolucion_reformulacion",
        "train",
        "Sistema que analiza datos de gestion para la toma de decisiones.",
        sponsor="El equipo de Transformacion Digital",
    ),
    _sol(
        "VAR-SOL-R08",
        "operativo",
        ["operativos"],
        "devolucion_reformulacion",
        "train",
        "Sistema que clasifica solicitudes de servicio.",
        sponsor="El comite de Operaciones",
    ),
    _sol(
        "VAR-SOL-R09",
        "negocio",
        ["personales"],
        "devolucion_reformulacion",
        "train",
        "Sistema que recomienda productos a clientes.",
        sponsor="El area de Marketing en su conjunto",
    ),
    _sol(
        "VAR-SOL-R10",
        "operativo",
        ["confidenciales"],
        "devolucion_reformulacion",
        "train",
        "Implementar una plataforma de IA generativa para documentos.",
        metricas="Implementacion exitosa de la plataforma",
    ),
    _sol(
        "VAR-SOL-R11",
        "negocio",
        ["personales"],
        "devolucion_reformulacion",
        "val",
        "Desplegar un LLM propio en atencion al cliente.",
        metricas="Despliegue en produccion",
    ),
    _sol(
        "VAR-SOL-R12",
        "operativo",
        ["operativos"],
        "devolucion_reformulacion",
        "val",
        "Sistema que mejora la calidad y agiliza el proceso de compras.",
        metricas="Mejorar calidad; agilizar el proceso",
    ),
    _sol(
        "VAR-SOL-R13",
        "operativo",
        ["confidenciales"],
        "devolucion_reformulacion",
        "val",
        "Sistema de analisis financiero.",
        sponsor="La direccion de Finanzas en general",
    ),
    _sol(
        "VAR-SOL-R14",
        "operativo",
        ["operativos"],
        "devolucion_reformulacion",
        "val",
        "Sistema que hace mas eficiente la logistica.",
        metricas="Hacer mas eficiente la operacion",
    ),
    _sol(
        "VAR-SOL-R15",
        "negocio",
        ["personales"],
        "devolucion_reformulacion",
        "val",
        "Instalar un chatbot con tecnologia de OpenAI.",
        metricas="Chatbot operativo en Q4",
    ),
    # devolucion_reformulacion -- ampliacion balanceada (4 train + 5 val + 10 test).
    # devolucion_no_ia ("no requiere IA") se RETIRO de solidez: no es criterio de
    # solidez del Marco; va a una etapa nueva (diferida, D-014). Idem "valor real".
    _sol(
        "VAR-SOL-R16",
        "operativo",
        ["operativos"],
        "devolucion_reformulacion",
        "train",
        "Adoptar Gemini para el area de operaciones.",
        metricas="Uso del modelo >= 80%",
    ),
    _sol(
        "VAR-SOL-R17",
        "negocio",
        ["personales"],
        "devolucion_reformulacion",
        "train",
        "Sistema que mejora la atencion y reduce costos.",
        metricas="Mejorar la atencion; reducir costos",
    ),
    _sol(
        "VAR-SOL-R18",
        "operativo",
        ["confidenciales"],
        "devolucion_reformulacion",
        "train",
        "Sistema que automatiza reportes de gestion.",
        sponsor="El comite de Direccion",
    ),
    _sol(
        "VAR-SOL-R19",
        "capacidad",
        ["ninguno"],
        "devolucion_reformulacion",
        "train",
        "Implementar RAG sobre los documentos del area.",
        metricas="Implementacion en Q2",
    ),
    _sol(
        "VAR-SOL-R20",
        "operativo",
        ["operativos"],
        "devolucion_reformulacion",
        "val",
        "Sistema que agiliza y mejora la gestion de proyectos.",
        metricas="Agilizar la gestion; mejorar el seguimiento",
    ),
    _sol(
        "VAR-SOL-R21",
        "operativo",
        ["confidenciales"],
        "devolucion_reformulacion",
        "val",
        "Sistema que clasifica documentos legales.",
        sponsor="El area Legal en su conjunto",
    ),
    _sol(
        "VAR-SOL-R22",
        "negocio",
        ["personales"],
        "devolucion_reformulacion",
        "val",
        "Desplegar un agente de IA en soporte tecnico.",
        metricas="Agente en produccion en Q3",
    ),
    _sol(
        "VAR-SOL-R23",
        "operativo",
        ["operativos"],
        "devolucion_reformulacion",
        "val",
        "Sistema que optimiza la experiencia del empleado.",
        metricas="Optimizar la experiencia del empleado",
    ),
    _sol(
        "VAR-SOL-R24",
        "operativo",
        ["operativos"],
        "devolucion_reformulacion",
        "val",
        "Sistema que prioriza tareas operativas.",
        sponsor="El equipo de Operaciones en general",
    ),
    _sol(
        "TST-SOL-R01",
        "negocio",
        ["personales"],
        "devolucion_reformulacion",
        "test",
        "Implementar Claude en el canal de ventas.",
        metricas="Adopcion >= 80%",
    ),
    _sol(
        "TST-SOL-R02",
        "operativo",
        ["operativos"],
        "devolucion_reformulacion",
        "test",
        "Sistema que mejora la productividad del equipo.",
        metricas="Mejorar la productividad",
    ),
    _sol(
        "TST-SOL-R03",
        "operativo",
        ["confidenciales"],
        "devolucion_reformulacion",
        "test",
        "Sistema que analiza la satisfaccion del cliente.",
        sponsor="El comite de Calidad",
    ),
    _sol(
        "TST-SOL-R04",
        "negocio",
        ["personales"],
        "devolucion_reformulacion",
        "test",
        "Adoptar una plataforma de IA generativa para marketing.",
        metricas="Plataforma operativa en Q4",
    ),
    _sol(
        "TST-SOL-R05",
        "operativo",
        ["operativos"],
        "devolucion_reformulacion",
        "test",
        "Sistema que hace mas eficiente el proceso de ventas.",
        metricas="Hacer mas eficiente el proceso",
    ),
    _sol(
        "TST-SOL-R06",
        "operativo",
        ["confidenciales"],
        "devolucion_reformulacion",
        "test",
        "Sistema que detecta riesgos operativos.",
        sponsor="La direccion de Riesgos en general",
    ),
    _sol(
        "TST-SOL-R07",
        "tecnico",
        ["operativos"],
        "devolucion_reformulacion",
        "test",
        "Desplegar un modelo de vision para control de calidad.",
        metricas="Modelo desplegado",
    ),
    _sol(
        "TST-SOL-R08",
        "operativo",
        ["operativos"],
        "devolucion_reformulacion",
        "test",
        "Sistema que mejora la toma de decisiones.",
        metricas="Mejorar la toma de decisiones",
    ),
    _sol(
        "TST-SOL-R09",
        "negocio",
        ["personales"],
        "devolucion_reformulacion",
        "test",
        "Sistema que automatiza la atencion de consultas.",
        sponsor="El area de Atencion en su conjunto",
    ),
    _sol(
        "TST-SOL-R10",
        "capacidad",
        ["ninguno"],
        "devolucion_reformulacion",
        "test",
        "Implementar un LLM open source en el area de datos.",
        metricas="Implementacion exitosa",
    ),
]


# ===========================================================================
# TRIAGE_FACTIBILIDAD: avanza_fast_gate / avanza_con_redisenio / no_avanza (3 clases del Marco)
# ===========================================================================
def _fac(cid, tipo, datos, label, split, decl, **kw):  # noqa: ANN001, ANN003
    return case(cid, tipo, datos, label, split, decl, **kw)


FACTIBILIDAD = [
    # avanza_fast_gate (8 train + 4 val): factible, plataforma homologada, revision humana
    _fac(
        "VAR-FAC-V01",
        "operativo",
        ["confidenciales"],
        "avanza_fast_gate",
        "train",
        "Sistema que resume reportes sobre plataforma interna homologada; la gerencia valida.",
        riesgo="Plataforma interna homologada; gerencia valida.",
    ),
    _fac(
        "VAR-FAC-V02",
        "negocio",
        ["personales"],
        "avanza_fast_gate",
        "train",
        "Recomendador que sugiere ofertas al representante en plataforma homologada; el representante decide.",
        impacto="Clientes via representante. Criticidad media.",
        riesgo="Plataforma homologada.",
        restr="Cumplimiento Ley 25.326; el representante decide.",
    ),
    _fac(
        "VAR-FAC-V03",
        "capacidad",
        ["ninguno"],
        "avanza_fast_gate",
        "train",
        "Asistente de minutas con modelo del catalogo corporativo; el autor valida.",
        riesgo="Modelo del catalogo; revision previa.",
    ),
    _fac(
        "VAR-FAC-V04",
        "operativo",
        ["operativos"],
        "avanza_fast_gate",
        "train",
        "Sistema que prioriza incidencias para el equipo tecnico; el equipo decide.",
        riesgo="Plataforma interna; el equipo decide.",
    ),
    _fac(
        "VAR-FAC-V05",
        "operativo",
        ["confidenciales"],
        "avanza_fast_gate",
        "train",
        "Analizador de clausulas con plataforma homologada; el abogado valida cada hallazgo.",
        impacto="Abogados como consumidores. Criticidad alta.",
        riesgo="Plataforma homologada.",
    ),
    _fac(
        "VAR-FAC-V06",
        "tecnico",
        ["operativos"],
        "avanza_fast_gate",
        "train",
        "Clasificador de logs sobre infraestructura interna homologada.",
        riesgo="Infraestructura interna homologada.",
    ),
    _fac(
        "VAR-FAC-V07",
        "operativo",
        ["confidenciales"],
        "avanza_fast_gate",
        "train",
        "Deteccion de anomalias de costos con plataforma interna; el analista valida.",
        riesgo="Plataforma interna homologada.",
    ),
    _fac(
        "VAR-FAC-V08",
        "negocio",
        ["personales"],
        "avanza_fast_gate",
        "train",
        "Resumen informativo del historial del cliente para el representante en CRM interno.",
        impacto="Representantes como usuarios; informativo. Criticidad media.",
        riesgo="CRM interno homologado.",
        restr="Cumplimiento Ley 25.326; el representante decide.",
    ),
    _fac(
        "VAR-FAC-V09",
        "operativo",
        ["operativos"],
        "avanza_fast_gate",
        "val",
        "Sistema que sugiere reposicion al comprador; el comprador decide.",
        riesgo="Plataforma interna; el comprador decide.",
    ),
    _fac(
        "VAR-FAC-V10",
        "capacidad",
        ["ninguno"],
        "avanza_fast_gate",
        "val",
        "Asistente SQL con modelo del catalogo; el analista revisa.",
        riesgo="Modelo del catalogo.",
    ),
    _fac(
        "VAR-FAC-V11",
        "operativo",
        ["confidenciales"],
        "avanza_fast_gate",
        "val",
        "Resumen de actas internas con plataforma homologada; los participantes validan.",
        riesgo="Plataforma homologada.",
    ),
    _fac(
        "VAR-FAC-V12",
        "operativo",
        ["operativos"],
        "avanza_fast_gate",
        "val",
        "Monitoreo que alerta al equipo NOC; el equipo decide intervenir.",
        riesgo="Plataforma interna; el equipo decide.",
    ),
    # avanza_con_redisenio (8 train + 4 val): autonomia reducible con etapa de revision humana previa
    _fac(
        "VAR-FAC-D01",
        "operativo",
        ["personales"],
        "avanza_con_redisenio",
        "train",
        "Agente que actualiza automaticamente datos del cliente en dos sistemas sin revision previa, miles por ciclo.",
        impacto="Clientes cuyos datos cambian. Criticidad alta.",
        riesgo="Revision del log ex-post (posterior al efecto).",
        restr="Cumplimiento Ley 25.326; sin modificar datos financieros.",
    ),
    _fac(
        "VAR-FAC-D02",
        "negocio",
        ["personales"],
        "avanza_con_redisenio",
        "train",
        "Sistema que aplica descuentos a clientes automaticamente sin aprobacion previa.",
        impacto="Clientes con descuentos. Criticidad media.",
        restr="Cumplimiento Defensa del Consumidor.",
    ),
    _fac(
        "VAR-FAC-D03",
        "operativo",
        ["personales"],
        "avanza_con_redisenio",
        "train",
        "Agente que cierra tickets y notifica al cliente automaticamente sin revision por caso.",
        impacto="Clientes notificados. Criticidad media.",
    ),
    _fac(
        "VAR-FAC-D04",
        "operativo",
        ["confidenciales"],
        "avanza_con_redisenio",
        "train",
        "Sistema que publica reportes a un tablero externo automaticamente sin validacion previa.",
        impacto="Audiencia interna amplia. Criticidad media.",
    ),
    _fac(
        "VAR-FAC-D05",
        "negocio",
        ["personales"],
        "avanza_con_redisenio",
        "train",
        "Agente que ajusta limites de servicio del cliente de forma automatica sin revision por caso.",
        impacto="Clientes afectados. Criticidad alta.",
        restr="Cumplimiento regulatorio.",
    ),
    _fac(
        "VAR-FAC-D06",
        "operativo",
        ["personales"],
        "avanza_con_redisenio",
        "train",
        "Agente que reasigna casos entre equipos automaticamente y comunica al cliente sin revision.",
        impacto="Clientes con cambios. Criticidad media.",
    ),
    _fac(
        "VAR-FAC-D07",
        "operativo",
        ["operativos"],
        "avanza_con_redisenio",
        "train",
        "Agente que ejecuta reinicios de servicios productivos de forma autonoma ante alertas.",
        impacto="Continuidad del servicio. Criticidad alta.",
    ),
    _fac(
        "VAR-FAC-D08",
        "negocio",
        ["personales"],
        "avanza_con_redisenio",
        "train",
        "Sistema que aprueba reintegros menores y los ejecuta automaticamente sin revision por caso.",
        impacto="Clientes con reintegros. Criticidad media.",
    ),
    _fac(
        "VAR-FAC-D09",
        "operativo",
        ["personales"],
        "avanza_con_redisenio",
        "val",
        "Agente que actualiza la direccion del cliente en sistemas core de forma automatica sin validacion.",
        impacto="Clientes cuyos datos cambian. Criticidad alta.",
    ),
    _fac(
        "VAR-FAC-D10",
        "negocio",
        ["personales"],
        "avanza_con_redisenio",
        "val",
        "Sistema que aplica bonificaciones automaticas a la factura sin aprobacion previa.",
        impacto="Clientes con bonificaciones. Criticidad media.",
    ),
    _fac(
        "VAR-FAC-D11",
        "operativo",
        ["operativos"],
        "avanza_con_redisenio",
        "val",
        "Agente que modifica configuraciones de red de forma autonoma ante desvios.",
        impacto="Continuidad del servicio. Criticidad alta.",
    ),
    _fac(
        "VAR-FAC-D12",
        "operativo",
        ["personales"],
        "avanza_con_redisenio",
        "val",
        "Agente que envia comunicaciones no estandar a clientes generadas y enviadas sin revision por caso.",
        impacto="Clientes destinatarios. Criticidad media.",
    ),
    # no_avanza (7 train + 4 val): factibilidad insuficiente (proveedor unico fuera de jurisdiccion, etc.)
    _fac(
        "VAR-FAC-N01",
        "operativo",
        ["confidenciales"],
        "no_avanza",
        "train",
        "Agente que analiza expedientes confidenciales con el unico proveedor capaz, que procesa fuera de jurisdiccion.",
        impacto="Abogados como usuarios. Criticidad alta.",
        riesgo="Proveedor unico fuera de jurisdiccion sin opcion local; sin alternativa viable.",
        restr="Secreto profesional; prohibido transferir a jurisdicciones sin proteccion equivalente.",
    ),
    _fac(
        "VAR-FAC-N02",
        "negocio",
        ["personales"],
        "no_avanza",
        "train",
        "Sistema que requiere un proveedor externo sin homologacion posible en el plazo del proyecto.",
        riesgo="Unico proveedor no cumple los requisitos de seguridad en el plazo; sin alternativa.",
        restr="Cumplimiento BCRA; sin proveedor homologado disponible.",
    ),
    _fac(
        "VAR-FAC-N03",
        "operativo",
        ["personales"],
        "no_avanza",
        "train",
        "Sistema de salud que necesita datos sensibles en un proveedor que no garantiza residencia local.",
        riesgo="Proveedor fuera de jurisdiccion; sin opcion on-premise ni region local.",
        restr="Datos de salud; prohibida la transferencia internacional.",
    ),
    _fac(
        "VAR-FAC-N04",
        "operativo",
        ["confidenciales"],
        "no_avanza",
        "train",
        "Sistema que depende de una tecnologia experimental no disponible para produccion en el plazo.",
        riesgo="Tecnologia inmadura; no hay version productiva disponible.",
        restr="Plazo del proyecto no negociable.",
    ),
    _fac(
        "VAR-FAC-N05",
        "negocio",
        ["personales"],
        "no_avanza",
        "train",
        "Sistema que exige integrar un core legacy sin API y sin posibilidad de modificacion ahora.",
        riesgo="Integracion tecnicamente inviable con el core actual; sin alternativa en el plazo.",
        restr="Sin presupuesto para reemplazar el core.",
    ),
    _fac(
        "VAR-FAC-N06",
        "operativo",
        ["confidenciales"],
        "no_avanza",
        "train",
        "Sistema que necesita un volumen de datos curados que no existe ni puede generarse en el plazo.",
        riesgo="No hay datos de calidad suficientes; su generacion excede el plazo.",
        restr="Sin dataset disponible.",
    ),
    _fac(
        "VAR-FAC-N07",
        "negocio",
        ["personales"],
        "no_avanza",
        "train",
        "Sistema que requiere una certificacion regulatoria que no estara disponible en el horizonte del proyecto.",
        riesgo="Certificacion pendiente sin fecha; bloquea el despliegue.",
        restr="Cumplimiento obligatorio antes de produccion.",
    ),
    _fac(
        "VAR-FAC-N08",
        "operativo",
        ["confidenciales"],
        "no_avanza",
        "val",
        "Agente legal con el unico proveedor capaz fuera de jurisdiccion, sin alternativa local.",
        riesgo="Proveedor unico fuera de jurisdiccion; sin alternativa.",
        restr="Secreto profesional; prohibida la transferencia.",
    ),
    _fac(
        "VAR-FAC-N09",
        "negocio",
        ["personales"],
        "no_avanza",
        "val",
        "Scoring que depende de un bureau externo sin acuerdo de proteccion de datos vigente.",
        riesgo="Proveedor sin acuerdo de proteccion; sin alternativa en el plazo.",
        restr="Cumplimiento Ley 25.326.",
    ),
    _fac(
        "VAR-FAC-N10",
        "operativo",
        ["confidenciales"],
        "no_avanza",
        "val",
        "Sistema que requiere infraestructura GPU no disponible ni adquirible en el plazo del proyecto.",
        riesgo="Sin capacidad de computo disponible en el plazo.",
        restr="Presupuesto y plazo fijos.",
    ),
    _fac(
        "VAR-FAC-N11",
        "operativo",
        ["personales"],
        "no_avanza",
        "val",
        "Sistema que necesita consentimiento explicito de clientes que no puede recolectarse a tiempo.",
        riesgo="Sin base de consentimiento; recolectarlo excede el plazo.",
        restr="Cumplimiento Ley 25.326.",
    ),
    # ── Ampliacion balanceada (3 clases del Marco) ──────────────────────────
    # Objetivo: train 12 / val 8 / test 8 por clase (macro-F1 medible). Se elimino
    # rechazo_formal (admisibilidad §9.2 / dedup §7.4 -> etapa futura). Frontera D/N:
    # D = autonomo REVERSIBLE de impacto medio (un ajuste acotado basta);
    # N = (a) inviable tecnico o (b) riesgo no aceptable (autonomo IRREVERSIBLE de alto
    # impacto sobre personas, donde el ajuste no alcanza).
    #
    # avanza_fast_gate (nuevos: 4 train + 4 val + 8 test)
    _fac(
        "VAR-FAC-V13",
        "operativo",
        ["confidenciales"],
        "avanza_fast_gate",
        "train",
        "Clasificador que enruta tickets entrantes al equipo en plataforma homologada; el equipo decide.",
        riesgo="Plataforma interna homologada; el equipo decide.",
    ),
    _fac(
        "VAR-FAC-V14",
        "capacidad",
        ["ninguno"],
        "avanza_fast_gate",
        "train",
        "Busqueda semantica sobre documentacion interna homologada; el usuario consulta y decide.",
        riesgo="Plataforma homologada; sin decision automatica.",
    ),
    _fac(
        "VAR-FAC-V15",
        "negocio",
        ["personales"],
        "avanza_fast_gate",
        "train",
        "Asistente que redacta respuestas a consultas frecuentes; el agente edita y envia.",
        impacto="Clientes via agente. Criticidad media.",
        restr="Cumplimiento Ley 25.326; el agente envia.",
    ),
    _fac(
        "VAR-FAC-V16",
        "operativo",
        ["operativos"],
        "avanza_fast_gate",
        "train",
        "Extractor de datos de facturas a un borrador que el contador revisa antes de cargar.",
        riesgo="Plataforma interna; el contador valida.",
    ),
    _fac(
        "VAR-FAC-V17",
        "operativo",
        ["confidenciales"],
        "avanza_fast_gate",
        "val",
        "Resumen de llamadas para el supervisor en plataforma homologada; informativo.",
        riesgo="Plataforma homologada.",
    ),
    _fac(
        "VAR-FAC-V18",
        "capacidad",
        ["ninguno"],
        "avanza_fast_gate",
        "val",
        "Traductor interno de documentacion con modelo del catalogo; el autor valida.",
        riesgo="Modelo del catalogo; revision previa.",
    ),
    _fac(
        "VAR-FAC-V19",
        "negocio",
        ["personales"],
        "avanza_fast_gate",
        "val",
        "Resumen del historial del cliente para el representante en CRM interno homologado; informativo.",
        impacto="Representantes como usuarios. Criticidad media.",
        restr="Cumplimiento Ley 25.326; informativo.",
    ),
    _fac(
        "VAR-FAC-V20",
        "operativo",
        ["operativos"],
        "avanza_fast_gate",
        "val",
        "Deteccion de anomalias de inventario que alerta al equipo; el equipo decide intervenir.",
        riesgo="Plataforma interna; el equipo decide.",
    ),
    _fac(
        "TST-FAC-V01",
        "operativo",
        ["confidenciales"],
        "avanza_fast_gate",
        "test",
        "Transcripcion de reuniones para los participantes en plataforma homologada.",
        riesgo="Plataforma homologada.",
    ),
    _fac(
        "TST-FAC-V02",
        "capacidad",
        ["ninguno"],
        "avanza_fast_gate",
        "test",
        "Buscador de jurisprudencia interna para el abogado, que valida cada cita.",
        riesgo="Consulta asistiva; el abogado decide.",
    ),
    _fac(
        "TST-FAC-V03",
        "operativo",
        ["operativos"],
        "avanza_fast_gate",
        "test",
        "Clasificador de correos internos que los enruta al area; el area decide.",
        riesgo="Plataforma interna; el area decide.",
    ),
    _fac(
        "TST-FAC-V04",
        "capacidad",
        ["ninguno"],
        "avanza_fast_gate",
        "test",
        "Generador de tests unitarios sugeridos para el desarrollador, que revisa y acepta.",
        riesgo="Modelo del catalogo; el dev revisa.",
    ),
    _fac(
        "TST-FAC-V05",
        "negocio",
        ["personales"],
        "avanza_fast_gate",
        "test",
        "Resumen de feedback de clientes para el equipo de producto; informativo.",
        impacto="Equipo de producto como usuario. Criticidad media.",
        restr="Cumplimiento Ley 25.326; informativo.",
    ),
    _fac(
        "TST-FAC-V06",
        "operativo",
        ["confidenciales"],
        "avanza_fast_gate",
        "test",
        "Asistente que indexa contratos para busqueda del abogado; consulta sin decision.",
        riesgo="Plataforma homologada; consulta.",
    ),
    _fac(
        "TST-FAC-V07",
        "capacidad",
        ["ninguno"],
        "avanza_fast_gate",
        "test",
        "Asistente de codigo con catalogo corporativo; el desarrollador acepta o descarta.",
        riesgo="Modelo del catalogo; el dev decide.",
    ),
    _fac(
        "TST-FAC-V08",
        "operativo",
        ["operativos"],
        "avanza_fast_gate",
        "test",
        "Priorizador de alertas de monitoreo para el NOC; el NOC decide la intervencion.",
        riesgo="Plataforma interna; el NOC decide.",
    ),
    # avanza_con_redisenio (nuevos: 4 train + 4 val + 8 test) -- autonomo REVERSIBLE,
    # impacto medio; agregar un control acotado basta.
    _fac(
        "VAR-FAC-D13",
        "operativo",
        ["personales"],
        "avanza_con_redisenio",
        "train",
        "Agente que cancela suscripciones de clientes automaticamente sin revision por caso.",
        impacto="Clientes con suscripcion. Criticidad media; reversible.",
    ),
    _fac(
        "VAR-FAC-D14",
        "negocio",
        ["personales"],
        "avanza_con_redisenio",
        "train",
        "Sistema que aplica recargos por mora a la factura de forma automatica sin revision.",
        impacto="Clientes facturados. Criticidad media; reversible.",
        restr="Cumplimiento Defensa del Consumidor.",
    ),
    _fac(
        "VAR-FAC-D15",
        "operativo",
        ["operativos"],
        "avanza_con_redisenio",
        "train",
        "Agente que reprograma entregas y notifica al cliente sin validacion previa.",
        impacto="Clientes con entregas. Criticidad media; reversible.",
    ),
    _fac(
        "VAR-FAC-D16",
        "negocio",
        ["personales"],
        "avanza_con_redisenio",
        "train",
        "Sistema que actualiza el segmento comercial del cliente y dispara campanias sin revision.",
        impacto="Clientes segmentados. Criticidad media; reversible.",
        restr="Cumplimiento Ley 25.326.",
    ),
    _fac(
        "VAR-FAC-D17",
        "operativo",
        ["personales"],
        "avanza_con_redisenio",
        "val",
        "Agente que actualiza la direccion del cliente en el CRM de forma automatica sin validacion.",
        impacto="Clientes cuyos datos cambian. Criticidad media; reversible.",
    ),
    _fac(
        "VAR-FAC-D18",
        "negocio",
        ["personales"],
        "avanza_con_redisenio",
        "val",
        "Sistema que aprueba devoluciones menores y emite el reembolso sin revision por caso.",
        impacto="Clientes con devoluciones. Criticidad media; reversible.",
    ),
    _fac(
        "VAR-FAC-D19",
        "operativo",
        ["operativos"],
        "avanza_con_redisenio",
        "val",
        "Agente que escala incidentes a proveedores externos de forma automatica sin acotar alcance.",
        impacto="Continuidad operativa. Criticidad media; reversible.",
    ),
    _fac(
        "VAR-FAC-D20",
        "negocio",
        ["personales"],
        "avanza_con_redisenio",
        "val",
        "Sistema que aplica bonificaciones a la factura del cliente sin aprobacion previa.",
        impacto="Clientes con bonificaciones. Criticidad media; reversible.",
    ),
    _fac(
        "TST-FAC-D01",
        "operativo",
        ["personales"],
        "avanza_con_redisenio",
        "test",
        "Agente que reasigna turnos de clientes y los notifica sin revision por caso.",
        impacto="Clientes con turnos. Criticidad media; reversible.",
    ),
    _fac(
        "TST-FAC-D02",
        "negocio",
        ["personales"],
        "avanza_con_redisenio",
        "test",
        "Sistema que ajusta el limite de descuento del vendedor de forma automatica sin aprobacion.",
        impacto="Operacion comercial. Criticidad media; reversible.",
    ),
    _fac(
        "TST-FAC-D03",
        "operativo",
        ["operativos"],
        "avanza_con_redisenio",
        "test",
        "Agente que reinicia servicios productivos ante alertas de forma autonoma sin revision.",
        impacto="Continuidad del servicio. Criticidad media; reversible.",
    ),
    _fac(
        "TST-FAC-D04",
        "negocio",
        ["personales"],
        "avanza_con_redisenio",
        "test",
        "Sistema que envia recordatorios de cobranza personalizados al cliente sin revision.",
        impacto="Clientes contactados. Criticidad media; reversible.",
        restr="Cumplimiento Ley 25.326.",
    ),
    _fac(
        "TST-FAC-D05",
        "operativo",
        ["personales"],
        "avanza_con_redisenio",
        "test",
        "Agente que cierra reclamos y responde al cliente automaticamente sin revision por caso.",
        impacto="Clientes con reclamos. Criticidad media; reversible.",
    ),
    _fac(
        "TST-FAC-D06",
        "operativo",
        ["operativos"],
        "avanza_con_redisenio",
        "test",
        "Agente que modifica reglas de ruteo de red ante desvios de forma autonoma sin revision.",
        impacto="Continuidad operativa. Criticidad media; reversible.",
    ),
    _fac(
        "TST-FAC-D07",
        "negocio",
        ["personales"],
        "avanza_con_redisenio",
        "test",
        "Sistema que actualiza datos de contacto del cliente en sistemas internos sin validacion.",
        impacto="Clientes cuyos datos cambian. Criticidad media; reversible.",
        restr="Cumplimiento Ley 25.326.",
    ),
    _fac(
        "TST-FAC-D08",
        "operativo",
        ["operativos"],
        "avanza_con_redisenio",
        "test",
        "Agente que publica reportes a un tablero externo de forma automatica sin validacion previa.",
        impacto="Audiencia interna amplia. Criticidad media; reversible.",
    ),
    # no_avanza (nuevos: 5 train + 4 val + 8 test) -- (a) inviable tecnico /
    # (b) riesgo no aceptable: autonomo IRREVERSIBLE de alto impacto sobre personas.
    _fac(
        "VAR-FAC-N12",
        "operativo",
        ["personales"],
        "no_avanza",
        "train",
        "Agente que ejecuta la baja laboral del empleado por score de desempenio sin intervencion.",
        impacto="Empleados. Criticidad muy alta; irreversible.",
        riesgo="Autonomia total sobre decision irreversible de alto impacto; el ajuste no alcanza.",
    ),
    _fac(
        "VAR-FAC-N13",
        "operativo",
        ["personales"],
        "no_avanza",
        "train",
        "Agente que corta el servicio esencial al cliente por mora de forma autonoma sin revision.",
        impacto="Clientes; perdida de acceso a servicio esencial. Irreversible.",
        riesgo="Autonomia sobre denegacion de servicio esencial; riesgo no aceptable.",
    ),
    _fac(
        "VAR-FAC-N14",
        "operativo",
        ["confidenciales"],
        "no_avanza",
        "train",
        "Sistema que requiere un modelo on-premise que el unico proveedor no ofrece; la nube esta vetada.",
        riesgo="Sin alternativa tecnica viable en el plazo.",
        restr="Prohibido procesar fuera de la organizacion; sin opcion on-premise.",
    ),
    _fac(
        "VAR-FAC-N15",
        "negocio",
        ["personales"],
        "no_avanza",
        "train",
        "Scoring que depende de un bureau externo sin acuerdo de proteccion de datos vigente ni alternativa.",
        riesgo="Proveedor sin acuerdo; sin alternativa en el plazo.",
        restr="Cumplimiento Ley 25.326.",
    ),
    _fac(
        "VAR-FAC-N16",
        "negocio",
        ["personales"],
        "no_avanza",
        "train",
        "Agente que ejecuta cambios vinculantes en contratos de clientes de forma autonoma sin revision.",
        impacto="Clientes con contratos. Criticidad muy alta; irreversible.",
        riesgo="Autonomia sobre decision contractual vinculante; riesgo no aceptable.",
    ),
    _fac(
        "VAR-FAC-N17",
        "operativo",
        ["confidenciales"],
        "no_avanza",
        "val",
        "Sistema que necesita un volumen de datos curados que no existe ni puede generarse en el plazo.",
        riesgo="Sin datos de calidad suficientes; su generacion excede el plazo.",
        restr="Sin dataset disponible.",
    ),
    _fac(
        "VAR-FAC-N18",
        "negocio",
        ["personales"],
        "no_avanza",
        "val",
        "Sistema que aprueba y desembolsa creditos de forma autonoma sin revision humana.",
        impacto="Solicitantes de credito. Criticidad muy alta; irreversible.",
        riesgo="Autonomia sobre decision financiera vinculante; riesgo no aceptable.",
        restr="Cumplimiento BCRA.",
    ),
    _fac(
        "VAR-FAC-N19",
        "operativo",
        ["operativos"],
        "no_avanza",
        "val",
        "Sistema que requiere infraestructura GPU no disponible ni adquirible en el plazo del proyecto.",
        riesgo="Sin capacidad de computo disponible en el plazo.",
        restr="Presupuesto y plazo fijos.",
    ),
    _fac(
        "VAR-FAC-N20",
        "operativo",
        ["personales"],
        "no_avanza",
        "val",
        "Agente que ejecuta retenciones sobre cuentas de clientes de forma autonoma sin revision.",
        impacto="Clientes; fondos retenidos. Criticidad muy alta; irreversible.",
        riesgo="Autonomia sobre accion financiera irreversible; riesgo no aceptable.",
    ),
    _fac(
        "TST-FAC-N01",
        "operativo",
        ["confidenciales"],
        "no_avanza",
        "test",
        "Sistema que depende de un proveedor cloud sin region local; los datos no pueden salir del pais.",
        riesgo="Sin region local ni alternativa on-premise.",
        restr="Prohibida la transferencia internacional.",
    ),
    _fac(
        "TST-FAC-N02",
        "operativo",
        ["personales"],
        "no_avanza",
        "test",
        "Agente que deniega el alta de un servicio esencial al cliente de forma autonoma sin revision.",
        impacto="Clientes; sin acceso a servicio esencial. Irreversible.",
        riesgo="Autonomia sobre denegacion de servicio esencial; riesgo no aceptable.",
    ),
    _fac(
        "TST-FAC-N03",
        "negocio",
        ["personales"],
        "no_avanza",
        "test",
        "Sistema que requiere una certificacion regulatoria que no estara disponible en el horizonte del proyecto.",
        riesgo="Certificacion pendiente sin fecha; bloquea el despliegue.",
        restr="Cumplimiento obligatorio antes de produccion.",
    ),
    _fac(
        "TST-FAC-N04",
        "operativo",
        ["personales"],
        "no_avanza",
        "test",
        "Agente que ejecuta sanciones disciplinarias a empleados de forma autonoma sin intervencion.",
        impacto="Empleados sancionados. Criticidad alta; irreversible.",
        riesgo="Autonomia sobre decision disciplinaria irreversible; riesgo no aceptable.",
    ),
    _fac(
        "TST-FAC-N05",
        "operativo",
        ["operativos"],
        "no_avanza",
        "test",
        "Sistema que depende de una tecnologia experimental sin version productiva disponible en el plazo.",
        riesgo="Tecnologia inmadura; no hay version productiva.",
        restr="Plazo del proyecto no negociable.",
    ),
    _fac(
        "TST-FAC-N06",
        "negocio",
        ["personales"],
        "no_avanza",
        "test",
        "Sistema que cancela polizas de seguro de clientes de forma autonoma sin revision.",
        impacto="Asegurados; perdida de cobertura. Irreversible.",
        riesgo="Autonomia sobre denegacion de cobertura esencial; riesgo no aceptable.",
        restr="Cumplimiento Superintendencia de Seguros.",
    ),
    _fac(
        "TST-FAC-N07",
        "operativo",
        ["confidenciales"],
        "no_avanza",
        "test",
        "Sistema que exige integrar un core legacy sin API y sin posibilidad de modificacion ahora.",
        riesgo="Integracion inviable con el core actual en el plazo.",
        restr="Sin presupuesto para reemplazar el core.",
    ),
    _fac(
        "TST-FAC-N08",
        "negocio",
        ["personales"],
        "no_avanza",
        "test",
        "Agente que ejecuta el cierre de cuentas bancarias de clientes de forma autonoma sin revision.",
        impacto="Clientes; cuenta cerrada. Criticidad muy alta; irreversible.",
        riesgo="Autonomia sobre decision financiera irreversible; riesgo no aceptable.",
        restr="Cumplimiento BCRA.",
    ),
]


# ===========================================================================
# FAST_GATE: Verde / Amarillo / Rojo / Negro
# ===========================================================================
def _fg(cid, tipo, datos, label, split, decl, **kw):  # noqa: ANN001, ANN003
    return case(cid, tipo, datos, label, split, decl, **kw)


FAST_GATE = [
    # Verde (8 train + 4 val): sin datos sensibles o solo operativos; informativo; revision humana; catalogo interno
    _fg(
        "VAR-FG-V01",
        "capacidad",
        ["ninguno"],
        "Verde",
        "train",
        "Asistente que genera borradores de minutas internas; el autor revisa antes de compartir.",
        impacto="Empleados como usuarios; no decide sobre personas. Criticidad baja.",
    ),
    _fg(
        "VAR-FG-V02",
        "operativo",
        ["operativos"],
        "Verde",
        "train",
        "Sistema que alerta al equipo tecnico ante desvios de metricas de infraestructura; el equipo decide.",
        impacto="Equipo tecnico como destinatario. Criticidad baja para personas.",
        restr="Alertas no automaticas sobre la red.",
    ),
    _fg(
        "VAR-FG-V03",
        "operativo",
        ["ninguno"],
        "Verde",
        "train",
        "Sistema que ordena correos internos por tema; el empleado decide que hacer.",
        impacto="Empleados como usuarios. Criticidad baja.",
    ),
    _fg(
        "VAR-FG-V04",
        "capacidad",
        ["ninguno"],
        "Verde",
        "train",
        "Asistente que sugiere cursos del catalogo interno al empleado; el empleado decide libremente.",
        impacto="Empleados; la decision es del empleado; sin impacto en desempeno. Criticidad baja.",
    ),
    _fg(
        "VAR-FG-V05",
        "operativo",
        ["operativos"],
        "Verde",
        "train",
        "Sistema que resume metricas operativas no sensibles para el equipo; la gerencia valida.",
        impacto="Gerentes como consumidores; no decide sobre personas. Criticidad baja.",
    ),
    _fg(
        "VAR-FG-V06",
        "capacidad",
        ["ninguno"],
        "Verde",
        "train",
        "Asistente que propone respuestas a tickets internos; el agente revisa antes de enviar.",
        impacto="Empleados como usuarios. Criticidad baja.",
    ),
    _fg(
        "VAR-FG-V07",
        "operativo",
        ["ninguno"],
        "Verde",
        "train",
        "Generador de borradores de documentacion interna a partir de notas; el autor aprueba.",
        impacto="Empleados como usuarios. Criticidad baja.",
    ),
    _fg(
        "VAR-FG-V08",
        "tecnico",
        ["operativos"],
        "Verde",
        "train",
        "Pipeline que clasifica logs tecnicos para el equipo de plataforma.",
        impacto="Equipo tecnico. Criticidad baja para personas.",
    ),
    _fg(
        "VAR-FG-V09",
        "capacidad",
        ["ninguno"],
        "Verde",
        "val",
        "Asistente que resume papers para el equipo de investigacion; ellos validan.",
        impacto="Empleados como usuarios. Criticidad baja.",
    ),
    _fg(
        "VAR-FG-V10",
        "operativo",
        ["operativos"],
        "Verde",
        "val",
        "Sistema que sugiere reposicion de stock al comprador; el comprador decide.",
        impacto="Empleados como usuarios. Criticidad baja.",
    ),
    _fg(
        "VAR-FG-V11",
        "operativo",
        ["ninguno"],
        "Verde",
        "val",
        "Asistente que traduce documentacion interna no sensible; el autor revisa.",
        impacto="Empleados como usuarios. Criticidad baja.",
    ),
    _fg(
        "VAR-FG-V12",
        "operativo",
        ["operativos"],
        "Verde",
        "val",
        "Tablero que resume indicadores operativos para gerentes; ninguna decision sobre personas depende del output.",
        impacto="Gerentes como consumidores. Criticidad baja.",
    ),
    # Amarillo (8 train + 4 val): datos personales/confidenciales + un factor mas (externo por homologar o reputacional), con revision humana
    _fg(
        "VAR-FG-A01",
        "capacidad",
        ["confidenciales"],
        "Amarillo",
        "train",
        "Asistente que resume actas internas usando un LLM externo que sera homologado; los participantes validan.",
        impacto="Empleados como usuarios. Criticidad baja.",
        riesgo="El LLM externo sera homologado antes del despliegue.",
        restr="Revision previa; cumplimiento Ley 25.326.",
    ),
    _fg(
        "VAR-FG-A02",
        "operativo",
        ["confidenciales"],
        "Amarillo",
        "train",
        "Sistema que genera contenido para canales publicos; el responsable aprueba antes de publicar.",
        impacto="Canal de salida publico; un error afecta la imagen. Criticidad alta.",
        restr="Normativa de defensa del consumidor sobre publicidad; revision previa.",
    ),
    _fg(
        "VAR-FG-A03",
        "negocio",
        ["personales"],
        "Amarillo",
        "train",
        "Recomendador de upgrade que el representante presenta; el representante decide.",
        impacto="Clientes via representante; el sistema condiciona la oferta. Criticidad media.",
        restr="Cumplimiento Ley 25.326 y Defensa del Consumidor; el representante decide.",
    ),
    _fg(
        "VAR-FG-A04",
        "operativo",
        ["confidenciales"],
        "Amarillo",
        "train",
        "Analizador de clausulas de contratos de clientes; el abogado valida cada hallazgo.",
        impacto="El analisis condiciona acciones legales sobre clientes. Criticidad alta.",
        restr="Confidencialidad contractual; el abogado valida.",
    ),
    _fg(
        "VAR-FG-A05",
        "capacidad",
        ["personales"],
        "Amarillo",
        "train",
        "Resumidor de reuniones con lista de participantes usando un LLM externo por homologar; validan los participantes.",
        impacto="Empleados como usuarios. Criticidad baja.",
        riesgo="El LLM externo sera homologado.",
        restr="Revision previa; cumplimiento Ley 25.326.",
    ),
    _fg(
        "VAR-FG-A06",
        "negocio",
        ["personales"],
        "Amarillo",
        "train",
        "Agente que envia comunicaciones de bienvenida predefinidas al cliente; contenido aprobado.",
        impacto="Clientes que reciben comunicaciones. Criticidad media.",
        restr="Cumplimiento Ley 26.951 No Llame y Ley 25.326; plantillas aprobadas.",
    ),
    _fg(
        "VAR-FG-A07",
        "operativo",
        ["confidenciales"],
        "Amarillo",
        "train",
        "Generador de comunicados para redes sociales corporativas; el responsable aprueba.",
        impacto="Audiencia externa publica; error afecta imagen. Criticidad alta.",
        restr="Normativa de defensa del consumidor; revision previa.",
    ),
    _fg(
        "VAR-FG-A08",
        "negocio",
        ["personales"],
        "Amarillo",
        "train",
        "Chatbot que propone soluciones estandar pre-aprobadas a reclamos; escala casos complejos a humano.",
        impacto="Clientes que interactuan; propone compensaciones. Criticidad alta.",
        restr="Defensa del Consumidor y ENACOM; escalada obligatoria.",
    ),
    _fg(
        "VAR-FG-A09",
        "capacidad",
        ["confidenciales"],
        "Amarillo",
        "val",
        "Asistente que resume documentos internos usando un LLM externo por homologar; el autor valida.",
        riesgo="El LLM externo sera homologado.",
        restr="Revision previa.",
    ),
    _fg(
        "VAR-FG-A10",
        "negocio",
        ["personales"],
        "Amarillo",
        "val",
        "Recomendador de productos que el representante presenta al cliente; el representante decide.",
        impacto="Clientes via representante. Criticidad media.",
        restr="Cumplimiento Ley 25.326; el representante decide.",
    ),
    _fg(
        "VAR-FG-A11",
        "operativo",
        ["confidenciales"],
        "Amarillo",
        "val",
        "Generador de contenido para el blog publico de la empresa; el responsable aprueba.",
        impacto="Audiencia externa. Criticidad alta.",
        restr="Defensa del consumidor; revision previa.",
    ),
    _fg(
        "VAR-FG-A12",
        "negocio",
        ["personales"],
        "Amarillo",
        "val",
        "Analizador de cumplimiento de contratos de clientes; el equipo legal valida.",
        impacto="Condiciona acciones sobre clientes. Criticidad alta.",
        restr="Confidencialidad; el abogado valida.",
    ),
    # Rojo (7 train + 4 val): personal + influye en decision + proveedor externo por homologar + legal, con revision humana
    _fg(
        "VAR-FG-R01",
        "negocio",
        ["personales"],
        "Rojo",
        "train",
        "Chatbot que accede a datos del cliente y responde en tiempo real con un LLM externo por homologar; escala a humano.",
        impacto="Clientes que interactuan; las respuestas influyen en sus decisiones. Criticidad alta.",
        riesgo="El LLM externo sera homologado antes del lanzamiento.",
        restr="Cumplimiento Ley 25.326; evaluacion de seguridad del proveedor pendiente.",
    ),
    _fg(
        "VAR-FG-R02",
        "negocio",
        ["personales"],
        "Rojo",
        "train",
        "Scoring crediticio con API externa por homologar; el analista registra la decision.",
        impacto="Clientes solicitantes; el score determina el acceso. Criticidad muy alta.",
        riesgo="La API externa sera homologada antes de produccion.",
        restr="Cumplimiento BCRA y Ley 25.326; prohibido sesgo discriminatorio.",
    ),
    _fg(
        "VAR-FG-R03",
        "negocio",
        ["personales"],
        "Rojo",
        "train",
        "Asistente de diagnostico que sugiere al medico con un modelo externo por homologar; el medico decide.",
        impacto="Pacientes; el sistema influye en el diagnostico. Criticidad muy alta.",
        riesgo="Modelo externo por homologar.",
        restr="Datos de salud; cumplimiento regulatorio; el medico decide.",
    ),
    _fg(
        "VAR-FG-R04",
        "negocio",
        ["personales"],
        "Rojo",
        "train",
        "Agente de reclamos que aplica automaticamente compensaciones acotadas al catalogo "
        "aprobado por policy; escala a un agente humano solo si el reclamo no encaja en el catalogo.",
        impacto="Clientes con reclamos resueltos dentro del catalogo aprobado. Criticidad alta.",
        riesgo="Accion autonoma acotada a un catalogo de resoluciones predefinido y aprobado.",
        restr="Cumplimiento Defensa del Consumidor; resoluciones limitadas al catalogo.",
    ),
    _fg(
        "VAR-FG-R05",
        "negocio",
        ["personales"],
        "Rojo",
        "train",
        "Motor de recomendacion de inversiones que asesora al cliente via asesor, con LLM externo por homologar.",
        impacto="Clientes; influye en decisiones financieras. Criticidad muy alta.",
        riesgo="LLM externo por homologar.",
        restr="Cumplimiento CNV y Ley 25.326; el asesor decide.",
    ),
    _fg(
        "VAR-FG-R06",
        "negocio",
        ["personales"],
        "Rojo",
        "train",
        "Chatbot legal que orienta al cliente con un modelo externo por homologar; el abogado revisa.",
        impacto="Clientes; influye en decisiones legales. Criticidad alta.",
        riesgo="Modelo externo por homologar.",
        restr="Secreto profesional; el abogado revisa.",
    ),
    _fg(
        "VAR-FG-R07",
        "negocio",
        ["personales"],
        "Rojo",
        "train",
        "Sistema que ajusta automaticamente el limite de credito de clientes dentro de bandas "
        "de politica vigente, sin discrecionalidad fuera de ellas; log mensual revisable por "
        "el equipo de credito dentro de las 48 horas.",
        impacto="Clientes pospago cuyos limites se ajustan dentro de bandas aprobadas. Criticidad alta.",
        riesgo="Ajuste autonomo acotado a bandas predefinidas, con revision sistematica del log dentro de 48hs.",
        restr="Cumplimiento BCRA; ajuste dentro de parametros de politica.",
    ),
    _fg(
        "VAR-FG-R08",
        "negocio",
        ["personales"],
        "Rojo",
        "val",
        "Chatbot de autoatencion con datos del cliente y LLM externo por homologar; escala a humano.",
        impacto="Clientes; influye en decisiones sobre su plan. Criticidad alta.",
        riesgo="LLM externo por homologar.",
        restr="Cumplimiento Ley 25.326; seguridad del proveedor pendiente.",
    ),
    _fg(
        "VAR-FG-R09",
        "negocio",
        ["personales"],
        "Rojo",
        "val",
        "Evaluador de siniestros que recomienda al liquidador con proveedor externo por homologar; el liquidador decide.",
        impacto="Clientes; condiciona la cobertura. Criticidad alta.",
        riesgo="Proveedor externo por homologar.",
        restr="Cumplimiento regulatorio; el liquidador decide.",
    ),
    _fg(
        "VAR-FG-R10",
        "negocio",
        ["personales"],
        "Rojo",
        "val",
        "Asistente de cobranzas que define la estrategia hacia el cliente con LLM externo por homologar; el gestor decide.",
        impacto="Clientes con deuda; influye en la gestion. Criticidad alta.",
        riesgo="LLM externo por homologar.",
        restr="Cumplimiento Defensa del Consumidor; el gestor decide.",
    ),
    _fg(
        "VAR-FG-R11",
        "operativo",
        ["personales"],
        "Rojo",
        "val",
        "Agente que ejecuta automaticamente el alta de un nuevo cliente en el CRM y "
        "facturacion al verificar los criterios de elegibilidad, sin intervencion del "
        "operador; confirma el alta al cliente por email.",
        impacto="Nuevos clientes que solicitan el alta del servicio. Criticidad alta.",
        riesgo="Alta autonoma sin revision previa por caso, pero es una accion favorable "
        "solicitada por el propio cliente.",
        restr="Cumplimiento Ley 25.326; alta dentro de los criterios de elegibilidad estandar.",
    ),
    # Negro (7 train + 4 val): ejecuta acciones de alto impacto sin revision humana previa por caso
    _fg(
        "VAR-FG-N01",
        "negocio",
        ["personales"],
        "Negro",
        "train",
        "Agente que ajusta automaticamente precios y descuentos de planes para mas del 10% "
        "de la base de clientes activos, segun parametros de mercado en tiempo real, sin "
        "bandas ni catalogo acotado.",
        impacto="Mas del 10% de la base de clientes activos. Criticidad muy alta.",
        riesgo="Ajuste autonomo sin bandas ni catalogo predefinido, aplicado a escala sobre la base.",
        restr="Cumplimiento regulatorio de comunicaciones comerciales y proteccion de datos.",
    ),
    _fg(
        "VAR-FG-N02",
        "operativo",
        ["personales"],
        "Negro",
        "train",
        "Agente que ejecuta cortes de servicio a clientes de forma autonoma segun un score "
        "de riesgo, sin aprobacion ni revision sistematica posterior; el corte no es "
        "reversible automaticamente.",
        impacto="Clientes cortados; perdida de acceso al servicio. Criticidad muy alta.",
        riesgo="Corte de servicio (denegacion de acceso) autonomo, sin revision sistematica "
        "ni mecanismo de reversion.",
        restr="Cumplimiento Ley de Defensa del Consumidor y ENACOM.",
    ),
    _fg(
        "VAR-FG-N03",
        "negocio",
        ["personales"],
        "Negro",
        "train",
        "Sistema que aprueba y ejecuta reintegros a clientes automaticamente sin revision por caso.",
        impacto="Clientes con reintegros. Criticidad alta.",
        riesgo="Ejecuta sin aprobacion previa por caso.",
        restr="Cumplimiento Defensa del Consumidor.",
    ),
    _fg(
        "VAR-FG-N04",
        "operativo",
        ["personales"],
        "Negro",
        "train",
        "Agente que bloquea cuentas de clientes de forma autonoma ante senales de riesgo, sin revision previa.",
        impacto="Clientes bloqueados. Criticidad muy alta.",
        riesgo="Bloqueo autonomo sin revision por caso.",
        restr="Cumplimiento BCRA.",
    ),
    _fg(
        "VAR-FG-N05",
        "negocio",
        ["personales"],
        "Negro",
        "train",
        "Sistema que evalua el perfil de riesgo crediticio de cada cliente en tiempo real y "
        "aprueba o rechaza la solicitud de credito de forma automatica, notificando el "
        "resultado sin intervencion humana.",
        impacto="Clientes solicitantes; el sistema decide el acceso al credito en base a su "
        "perfil de riesgo. Criticidad muy alta.",
        riesgo="Decision financiera (otorga o deniega acceso al credito) basada en "
        "perfilamiento automatizado, sin revision humana.",
        restr="Cumplimiento BCRA y Ley 25.326.",
    ),
    _fg(
        "VAR-FG-N06",
        "operativo",
        ["personales"],
        "Negro",
        "train",
        "Agente que detecta incumplimientos contractuales de clientes corporativos y "
        "ejecuta automaticamente la terminacion del contrato al superar el umbral "
        "definido, sin intervencion humana previa; la terminacion es irreversible.",
        impacto="Clientes corporativos con contrato terminado de forma permanente. Criticidad maxima.",
        riesgo="Terminacion de contrato irreversible sin intervencion manual posterior, "
        "ejecutada de forma autonoma.",
        restr="Cumplimiento Ley de Defensa del Consumidor; validacion legal de umbrales.",
    ),
    _fg(
        "VAR-FG-N07",
        "operativo",
        ["personales"],
        "Negro",
        "train",
        "Agente que perfila automaticamente el riesgo de abandono de cada cliente segun su "
        "comportamiento de consumo y ejecuta de forma autonoma ofertas de retencion "
        "vinculantes (descuentos contractuales) basadas en ese perfil, sin aprobacion por caso.",
        impacto="Clientes perfilados y con ofertas vinculantes aplicadas. Criticidad alta.",
        riesgo="Perfilamiento automatizado del comportamiento del cliente que dispara "
        "acciones vinculantes autonomas, sin revision.",
        restr="Cumplimiento Ley de Defensa del Consumidor y Ley 25.326.",
    ),
    _fg(
        "VAR-FG-N08",
        "operativo",
        ["personales"],
        "Negro",
        "val",
        "Agente que da de baja servicios de clientes automaticamente segun reglas de riesgo, sin revision previa.",
        impacto="Clientes dados de baja. Criticidad muy alta.",
        riesgo="Baja autonoma sin revision por caso.",
        restr="Cumplimiento regulatorio.",
    ),
    _fg(
        "VAR-FG-N09",
        "negocio",
        ["personales"],
        "Negro",
        "val",
        "Sistema que aplica penalidades a clientes y las ejecuta automaticamente sin intervencion humana.",
        impacto="Clientes penalizados. Criticidad alta.",
        riesgo="Penalidad autonoma sin revision.",
        restr="Cumplimiento Defensa del Consumidor.",
    ),
    _fg(
        "VAR-FG-N10",
        "operativo",
        ["personales"],
        "Negro",
        "val",
        "Agente que reasigna recursos criticos de produccion de forma autonoma con impacto en clientes, sin revision.",
        impacto="Clientes afectados por el servicio. Criticidad muy alta.",
        riesgo="Reasignacion autonoma de alto impacto sin revision previa.",
        restr="Cumplimiento regulatorio.",
    ),
    _fg(
        "VAR-FG-N11",
        "negocio",
        ["personales"],
        "Negro",
        "val",
        "Sistema que ejecuta ajustes de tarifa al cliente de forma automatica sin aprobacion por caso.",
        impacto="Clientes con cambios de tarifa. Criticidad alta.",
        riesgo="Ajuste autonomo sin revision previa.",
        restr="Cumplimiento Defensa del Consumidor y ENACOM.",
    ),
]


# Razonamiento por caso para los demos de fast_gate (few-shot rico). Solo los 30 de
# train: son los unicos que `LabeledFewShot` puede inyectar como demos; val/test no se
# usan como demos y `razonamiento` esta en `ignore_in_metric`. Justifican el color para
# dar senal de cadena-de-razonamiento (cot) a los demos, que sin esto iban vacios.
_FG_RAZONAMIENTO: dict[str, str] = {
    # Verde: uso interno de baja criticidad, sin decision sensible, con revision humana.
    "VAR-FG-V01": "Verde: uso interno de baja criticidad, sin datos sensibles ni decision sobre personas; el autor revisa antes de compartir.",
    "VAR-FG-V02": "Verde: datos operativos no sensibles y alerta no automatica; el equipo tecnico decide la intervencion.",
    "VAR-FG-V03": "Verde: sin datos sensibles, el empleado decide que hacer; sin impacto sobre terceros.",
    "VAR-FG-V04": "Verde: la decision queda en el empleado, sin impacto en su desempeno ni datos sensibles.",
    "VAR-FG-V05": "Verde: datos operativos no sensibles y no decide sobre personas; la gerencia valida.",
    "VAR-FG-V06": "Verde: uso interno y el agente revisa antes de enviar; sin datos sensibles.",
    "VAR-FG-V07": "Verde: documentacion interna y el autor aprueba; sin impacto en personas.",
    "VAR-FG-V08": "Verde: datos tecnicos internos, sin impacto en personas externas.",
    # Amarillo: datos personales/confidenciales + un factor mas, con revision humana.
    "VAR-FG-A01": "Amarillo: datos confidenciales y proveedor externo aun por homologar, mitigado por revision humana previa.",
    "VAR-FG-A02": "Amarillo: salida a un canal publico con riesgo reputacional, acotado por aprobacion previa del responsable.",
    "VAR-FG-A03": "Amarillo: datos personales y condiciona la oferta al cliente, pero el representante decide.",
    "VAR-FG-A04": "Amarillo: datos confidenciales que condicionan acciones legales sobre clientes; el abogado valida cada hallazgo.",
    "VAR-FG-A05": "Amarillo: datos personales y proveedor externo por homologar, con validacion humana de los participantes.",
    "VAR-FG-A06": "Amarillo: contacto con clientes y datos personales, mitigado por plantillas de contenido aprobadas.",
    "VAR-FG-A07": "Amarillo: exposicion publica con riesgo de imagen, acotada por revision previa del responsable.",
    "VAR-FG-A08": "Amarillo: interaccion con clientes en reclamos, limitada a respuestas pre-aprobadas y con escalada a humano.",
    # Rojo: personal + influye en decision + proveedor externo por homologar, con revision.
    "VAR-FG-R01": "Rojo: datos personales, influye en decisiones del cliente y usa un LLM externo aun por homologar; mitigado por escalada a humano.",
    "VAR-FG-R02": "Rojo: condiciona el acceso a credito con una API externa por homologar; el analista registra la decision.",
    "VAR-FG-R03": "Rojo: influye en un diagnostico medico con un modelo externo por homologar; el medico decide.",
    "VAR-FG-R04": "Rojo: resuelve reclamos de forma autonoma sin revision por caso, pero acotado a un catalogo de compensaciones aprobado; fuera del catalogo escala a humano.",
    "VAR-FG-R05": "Rojo: influye en decisiones financieras del cliente con un LLM externo por homologar; el asesor decide.",
    "VAR-FG-R06": "Rojo: influye en decisiones legales del cliente con un modelo externo por homologar; el abogado revisa.",
    "VAR-FG-R07": "Rojo: ajusta limites de credito de forma autonoma sin revision por caso, pero acotado a bandas de politica con revision sistematica del log dentro de 48hs y reversible; el moderador de escalada lo mantiene en Rojo.",
    # Negro: ejecuta acciones de alto impacto sin revision humana previa por caso.
    "VAR-FG-N01": "Negro: ajusta precios y descuentos de forma autonoma sobre mas del 10% de la base de clientes, sin bandas ni catalogo acotado ni revision por caso; alto impacto por escala.",
    "VAR-FG-N02": "Negro: corta el servicio (denegacion de acceso, criterio de naturaleza) de forma autonoma sin revision sistematica ni reversion -- P5=Si y alto impacto por naturaleza (criterio b).",
    "VAR-FG-N03": "Negro: aprueba y ejecuta reintegros de forma autonoma, sin revision humana por caso.",
    "VAR-FG-N04": "Negro: bloquea cuentas de clientes de forma autonoma ante senales de riesgo, sin revision previa.",
    "VAR-FG-N05": "Negro: perfila automaticamente el riesgo crediticio y decide el acceso al credito (naturaleza financiera, criterio b; profiling, criterio e) sin revision -- P5=Si y alto impacto.",
    "VAR-FG-N06": "Negro: termina contratos de forma autonoma e irreversible sin intervencion manual posterior -- P5=Si y alto impacto por irreversibilidad (criterio c).",
    "VAR-FG-N07": "Negro: perfila automaticamente el comportamiento del cliente (profiling, criterio e) y ejecuta ofertas vinculantes basadas en ese perfil sin revision -- P5=Si y alto impacto.",
}

# Anotacion de las 5 preguntas Si/No del Marco + alto_impacto por VAR-FG (D-013,
# arquitectura determinista). Cada tupla es (p1, p2, p3, p4, p5, alto_impacto) y es
# conteo-consistente con el color: derive_color(p1..p5, alto_impacto) == label.
# Columnas extra del fast_gate; el resto de etapas no las usa.
_FG_COLS_EXTRA: tuple[str, ...] = ("p1", "p2", "p3", "p4", "p5", "alto_impacto")
_FG_PREGUNTAS: dict[str, tuple[str, str, str, str, str, str]] = {
    "VAR-FG-A01": ("si", "si", "si", "No", "No", "No"),
    "VAR-FG-A02": ("si", "si", "No", "si", "No", "No"),
    "VAR-FG-A03": ("si", "si", "No", "si", "No", "No"),
    "VAR-FG-A04": ("si", "si", "No", "si", "No", "No"),
    "VAR-FG-A05": ("si", "si", "si", "No", "No", "No"),
    "VAR-FG-A06": ("si", "si", "No", "si", "No", "No"),
    "VAR-FG-A07": ("si", "si", "No", "si", "No", "No"),
    "VAR-FG-A08": ("si", "si", "No", "si", "No", "No"),
    "VAR-FG-A09": ("si", "si", "si", "No", "No", "No"),
    "VAR-FG-A10": ("si", "si", "No", "si", "No", "No"),
    "VAR-FG-A11": ("si", "si", "No", "si", "No", "No"),
    "VAR-FG-A12": ("si", "si", "No", "si", "No", "No"),
    "VAR-FG-N01": ("si", "si", "No", "si", "si", "si"),
    "VAR-FG-N02": ("si", "si", "No", "si", "si", "si"),
    "VAR-FG-N03": ("si", "si", "No", "si", "si", "si"),
    "VAR-FG-N04": ("si", "si", "No", "si", "si", "si"),
    "VAR-FG-N05": ("si", "si", "No", "si", "si", "si"),
    "VAR-FG-N06": ("si", "si", "No", "si", "si", "si"),
    "VAR-FG-N07": ("si", "si", "No", "si", "si", "si"),
    "VAR-FG-N08": ("si", "si", "No", "si", "si", "si"),
    "VAR-FG-N09": ("si", "si", "No", "si", "si", "si"),
    "VAR-FG-N10": ("si", "si", "No", "si", "si", "si"),
    "VAR-FG-N11": ("si", "si", "No", "si", "si", "si"),
    "VAR-FG-R01": ("si", "si", "si", "si", "No", "No"),
    "VAR-FG-R02": ("si", "si", "si", "si", "No", "No"),
    "VAR-FG-R03": ("si", "si", "si", "si", "No", "No"),
    "VAR-FG-R04": ("si", "si", "No", "si", "si", "No"),
    "VAR-FG-R05": ("si", "si", "si", "si", "No", "No"),
    "VAR-FG-R06": ("si", "si", "si", "si", "No", "No"),
    "VAR-FG-R07": ("si", "si", "No", "si", "si", "No"),
    "VAR-FG-R08": ("si", "si", "si", "si", "No", "No"),
    "VAR-FG-R09": ("si", "si", "si", "si", "No", "No"),
    "VAR-FG-R10": ("si", "si", "si", "si", "No", "No"),
    "VAR-FG-R11": ("si", "si", "No", "si", "si", "No"),
    "VAR-FG-V01": ("No", "No", "No", "No", "No", "No"),
    "VAR-FG-V02": ("No", "No", "No", "No", "No", "No"),
    "VAR-FG-V03": ("No", "No", "No", "No", "No", "No"),
    "VAR-FG-V04": ("No", "No", "No", "No", "No", "No"),
    "VAR-FG-V05": ("No", "No", "No", "No", "No", "No"),
    "VAR-FG-V06": ("No", "No", "No", "No", "No", "No"),
    "VAR-FG-V07": ("No", "No", "No", "No", "No", "No"),
    "VAR-FG-V08": ("No", "No", "No", "No", "No", "No"),
    "VAR-FG-V09": ("No", "No", "No", "No", "No", "No"),
    "VAR-FG-V10": ("No", "No", "No", "No", "No", "No"),
    "VAR-FG-V11": ("No", "No", "No", "No", "No", "No"),
    "VAR-FG-V12": ("No", "No", "No", "No", "No", "No"),
}

for _c in FAST_GATE:
    if _c["id"] in _FG_RAZONAMIENTO:
        _c["razonamiento"] = _FG_RAZONAMIENTO[_c["id"]]
    if _c["id"] in _FG_PREGUNTAS:
        for _col, _val in zip(_FG_COLS_EXTRA, _FG_PREGUNTAS[_c["id"]], strict=True):
            _c[_col] = _val


STAGE_CASES: dict[str, list[dict[str, str]]] = {
    "intake": INTAKE,
    "triage_solidez": SOLIDEZ,
    "triage_factibilidad": FACTIBILIDAD,
    "fast_gate": FAST_GATE,
}


def write_variations(out_dir: Path) -> dict[str, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}
    for stage, cases in STAGE_CASES.items():
        # fast_gate agrega las 5 preguntas + alto_impacto (arquitectura rule_derived).
        extra = list(_FG_COLS_EXTRA) if stage == "fast_gate" else []
        header = [*_FICHA_COLS, *extra, "label", "razonamiento", "split"]
        path = out_dir / f"flujo_intents_{stage}_var.csv"
        with open(path, "w", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=header, delimiter=";")
            writer.writeheader()
            for c in cases:
                writer.writerow({k: c.get(k, "" if k in extra else "false") for k in header})
        written[stage] = path
    return written


def main() -> None:
    pkg_dir = Path(__file__).resolve().parent.parent  # dspy_gepa_poc/
    out_dir = pkg_dir / "datasets" / "variations"
    written = write_variations(out_dir)
    from collections import Counter

    for stage, path in written.items():
        labels = Counter(c["label"] for c in STAGE_CASES[stage])
        splits = Counter(c["split"] for c in STAGE_CASES[stage])
        print(f"[{stage}] {path.name}: labels={dict(labels)} splits={dict(splits)}")


if __name__ == "__main__":
    main()
